name: checkmarx test

on:
  pull_request:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: dbrenecki/renovate-debug/.github/actions/checkmarx@checkmarx-v0.0.1
